### ISSUE TITLE
Simple user + password login with "remember me" feature

### ISSUE THREAD

**Issue by aromatt** [aromatt/thejub.pub#1]

**Comment by aromatt** [comment]
https://en.wikipedia.org/wiki/Single-page_application#JavaScript_frameworks

**Comment by aromatt** [comment]
http://passportjs.org/

**Comment by acowinthecrowd** [comment]
I'd like when accounts are set up, optional field for real name, and then if you're mentioned via username or real name, it bolds.

**Comment by jeskaeli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Simple user + password login with "remember me" feature #1 ?](https://trello.com/c/TT9IxIJg/16-simple-user-password-login-with-remember-me-feature-1)

**Comment by aromatt** [comment]
I think this is done enough.  Sessions don't refresh themselves yet but I'll create a new ticket for that.
