### ISSUE TITLE
toggle repeating of playlists

### ISSUE THREAD

**Issue by acowinthecrowd** [aromatt/thejub.pub#114]
With videos now moving to the bottom of your queue, there may only be one video in your queue so it keeps playing over and over again, wasting 2 seconds of your life each time.

If we could toggle repeating of playlists, I think that would be ideal

**Comment by aromatt** [comment]
maybe a setting like "Don't play recently-played videos" -- enabled by default (so default is to disallow playing recently-played videos)

**Comment by aromatt** [comment]
I'm going to pick this up next.  For now this will just be always on -- to override it so that a track will play again, the user will need to actively leave the DJ rotation and rejoin.

**Comment by aromatt** [comment]
I think each video in a queue will have a 'last played at' field.  Videos that were played within the past 8 hours will be tinted some color and will be skipped.  Leaving the DJ chair will clear all the 'last played at' fields.  Later, we can add a switch to the UI which always allows recently-played videos to play, and get rid of the leave-DJ-chair override.

**Comment by aromatt** [comment]
For now I'm just adding a toggle for video requeues
