### ISSUE TITLE
chat-bot meme generation

### ISSUE THREAD

**Issue by aromatt** [aromatt/thejub.pub#122]
http://version1.api.memegenerator.net/

**Comment by aromatt** [comment]
@acowinthecrowd

**Comment by acowinthecrowd** [comment]
My preferred method would be via chat command
/meme [meme name] [top text]/[bottom text]
So for the one I posted of Pepperidge Justin Remembers, it would be:
/meme pjr remember when culture wasn't consumed by the internet/justin remembers

And ideally, the image itself is displayed in chat for all that have images enabled. #36

**Comment by aromatt** [comment]
moved to wiki
