### ISSUE TITLE
Underscore

### ISSUE THREAD

**Issue by aromatt** [aromatt/thejub.pub#124]
Just discovered underscore https://github.com/jashkenas/underscore
Fills a lot of the gaps I have been trying to fill myself.  Should probably see how much overlap it has with the new Node 4.0/5.0 stuff.

**Comment by atrivedi** [comment]
No - you want https://lodash.com/  is better. Have used both. Lodash has so much more and is faster at times

**Comment by aromatt** [comment]
I think what I REALLY want is to program in a language that has less redundancy in its libraries...

**Comment by aromatt** [comment]
ah, lodash started as a fork of underscore and a 2 minute googling seems to indicate the community has aligned behind it.  so not really "redundant."  I'm sold

**Comment by atrivedi** [comment]
:+1: I swear by `lodash`

**Comment by acowinthecrowd** [comment]
Ankit, you shouldn't swear. It's not nice.

**Comment by atrivedi** [comment]
You're not my dad! :family:
