### ISSUE TITLE
embolden chat mentions

### ISSUE THREAD

**Issue by aromatt** [aromatt/thejub.pub#13]
if someone mentions you, "(1)" should show up in the browser tab

**Comment by acowinthecrowd** [comment]
The message that mentions you should also be bolded, or otherwise modified to stand out

**Comment by aromatt** [comment]
the browser tab part of this is done

**Comment by acowinthecrowd** [comment]
If jub is muted, the sound should still play

**Comment by aromatt** [comment]
hmm, ok separate toggle for chat sounds

**Comment by acowinthecrowd** [comment]
I hate that we keep adding stuff to he UI but thems the breaks huh kid

**Comment by croasus** [comment]
Discussed that the manifestation of this will be that in the mentionee's chat UI, the mentioner's message will be bolded and colored in the color of the mentioner's chat color.

**Comment by aromatt** [comment]
yeah, and if that's too hard to read, we can just bold it and leave the color as is (maybe color the mentionee's name?)

Other ideas:
  - brighten/blink the chat tab
  - color the background of the message differently

**Comment by aromatt** [comment]
We've got an implementation of this which a few of us at least are happy with, so I'm closing this for now.
