### ISSUE TITLE
Cannot access bottommost queue tracks if queue scrolls

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/thejub.pub#160]
The 'Github' link and chat input box component now overlaps with the bottom of the queue, hiding the bottom 2-ish tracks so that they are inaccessible.

This is a problem when adding new tracks, making it impossible to Move to Top.

![hiddentracks](https://cloud.githubusercontent.com/assets/14909827/12552740/8e806afe-c341-11e5-8198-72809ca9499b.png)

EDIT: I confirmed this actually only happened in Chrome when I had downloaded something (the download bar was being displayed - when I closed that bar, this problem was resolved)

**Comment by aromatt** [comment]
I can reproduce this by:
- Clicking on playlists
- making my browser to narrow
- clicking on Queue

**Comment by aromatt** [comment]
and whenever I see it, resizing the window at all fixes it

**Comment by aromatt** [comment]
I wasn't able to reproduce this the download bar way, but the fix I made fixed the instance I saw and hopefully the fix I made works for yours too.  Reopen if you see it again!
