### ISSUE TITLE
Empty playlist: Add prompt to queue list and suppress shuffle button

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/thejub.pub#165]
Currently, if there are no tracks in a playlist, the queue section looks odd. See below:

![empty queue](https://cloud.githubusercontent.com/assets/14909827/12655292/35c1b882-c5c6-11e5-8a69-29fd12a59080.png)

If there are no tracks in the currently selected playlist, I'd like to see a prompt. For example:

"There are no tracks in this playlist yet."
"There are currently no tracks defined for this playlist."
"There are currently no tracks in this playlist."
"You have not yet added any tracks to this playlist."

This wording could also include a brief instruction on how to add tracks (e.g., "Enter a search string in the search bar to find tracks, or paste the YouTube video link into the search bar directly.")

Additionally, the shuffle button should not display. The black background associated with the queue/playlist should not extend to the prompt. See suggestion mockup below:

![empty queue 2](https://cloud.githubusercontent.com/assets/14909827/12655663/09ae89d0-c5c8-11e5-9002-efd18bad91f4.png)

**Comment by aromatt** [comment]
Good idea - and it's easy!
