### ISSUE TITLE
Add tooltip for track name

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/thejub.pub#175]
If the track name is truncated, the only way to see the full name at this time is to look at the jubbot prompt. That's inconvenient if that prompt has been chatted offscreen.

I'd love to have a tooltip display when I hover on the track name that displays the full track name.

**Comment by jeskaeli** [comment]
@aromatt Hey, looks like you added the tooltip to the queue, but not the currently playing track, so this does not solve my issue!

**Comment by aromatt** [comment]
Woops, I didn't even read the ticket.  Fixed now.
