### ISSUE TITLE
Ability to crop video

### ISSUE THREAD

**Issue by aromatt** [aromatt/thejub.pub#178]
When a music video has a long intro, or a bunch of extra stuff at the end, and you only want to play the actual music part.

  - Initiate by right-clicking on the track and clicking "Crop video..."
  - A modal menu pops up with two text input boxes, for start time and end time
    - this will leave room for a future where the user can interact with a mini video player to crop the video.

**Comment by croasus** [comment]
Implementation Option 1: no "clip submit" button, but rather pressing enter from one of the boxes submits the video clip.

![no button](https://cloud.githubusercontent.com/assets/3858269/15310592/7f243b9a-1bbf-11e6-8dcb-0c1968f667f4.png)

**Comment by croasus** [comment]
A couple of implementation options illustrated below. Implementation 2 should have the scissors in the track line item - just for ease of taking the screenshot, it didn't (just pretend it's scissors instead).

Should the slider bar jump around as you edit the text box time values in real time?

Implementation Option 1: no "clip submit" button, but rather pressing enter from one of the boxes submits the video clip.
![no button](https://cloud.githubusercontent.com/assets/3858269/15310623/cd493208-1bbf-11e6-9249-ad66b250beee.png)

Implementation Option 2: Green checkmark "clip submit" button. 
![with button](https://cloud.githubusercontent.com/assets/3858269/15310614/a9490284-1bbf-11e6-9228-58fa6e57ed83.png)

**Comment by acowinthecrowd** [comment]
Does jubbot's daily update (* Added track-clipping feature (++croasus)) give Whit karma every time a user refreshes while he's in the room? Will test today

**Comment by aromatt** [comment]
what's the answer?

**Comment by acowinthecrowd** [comment]
Hasn't joined yet

**Comment by acowinthecrowd** [comment]
It does not appear to.

**Comment by jeskaeli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#178: Ability to crop video](https://trello.com/c/lTycJ95l/40-178-ability-to-crop-video)
