### ISSUE TITLE
Add Search icon to the left of search box that opens youtube

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/thejub.pub#192]
In the meantime until we have a fully functioning internal search with a preview capabiity, it might be nice (convenient) to have a search icon to the left of the search box that opens youtube in a new tab. Anyone who wants to preview videos before adding them must open youtube manually at this time.

![search icon](https://cloud.githubusercontent.com/assets/14909827/13223228/64f2ab36-d951-11e5-990f-0541bdeb942d.png)

**Comment by aromatt** [comment]
I'd rather let users keep a youtube bookmark in their bookmark bar in the interest of keeping the UI as minimal as possible.
