### ISSUE TITLE
Display karma in the Who's Jubbin list

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/thejub.pub#195]
I dislike having to announce to the chat that I'm looking at someone's karma (especially my own). I think it would be natural to display everyone's karma persistently in the Who's Jubbin list. For example:

![karma](https://cloud.githubusercontent.com/assets/14909827/13362228/0a0cf468-dc91-11e5-9e01-4324c4d08af3.jpg)

**Comment by jeskaeli** [comment]
Depending on how karma is perceived in general, it might be fun to even rank this list in order of karma.

**Comment by aromatt** [comment]
Also, jubbot doesn't seem to announce the karma periodically anymore.  I need to either fix that or remove the code that's supposed to be doing it.

**Comment by aromatt** [comment]
Implemented by https://github.com/aromatt/thejub.pub/commit/30aebc21f5707d1b64752550b53862d79a56399e
