### ISSUE TITLE
Test framework

### ISSUE THREAD

**Issue by aromatt** [aromatt/thejub.pub#2]
What's the node.js way to do tests?

**Comment by aromatt** [comment]
We'll need some fake data or we'll need to mock out the DB functions

**Comment by aromatt** [comment]
Github suggests some CI tools for running tests automatically: https://github.com/integrations/feature/build

**Comment by aromatt** [comment]
A good first candidate module for this would be the chat view.

**Comment by aromatt** [comment]
@atrivedi suggested jasmine http://jasmine.github.io/

**Comment by aromatt** [comment]
I think I would like to use the 'baselining' paradigm for this project.  The regress/ directory now contains a baseline tool and one regression test.  It would be cool to hook in an integration that will run the tests on each pull request. http://docs.travis-ci.com/user/pull-requests/

**Comment by atrivedi** [comment]
neat! that sounds like a good move

**Comment by aromatt** [comment]
http://docs.travis-ci.com/user/languages/javascript-with-nodejs

**Comment by aromatt** [comment]
We now have Travis CI running tests for each push to the main repo, and also on each PR.  Notes:
 - We can use Nock for recording HTTP traffic, so we'll probably use that for testing our interfaces to external APIs.
 - I should probably rewrite the `test/baseline` in node so that it will run on Windows.
 - For integration testing including sockets, we can just create some client sockets to represent users.
 - We should pick a headless browser to use for UI tests.
 - I'd like to avoid requiring a live mongo instance to run DB-touching tests, but I'm ok with recording the traffic for integration tests, if we can (meaning that adding new DB tests or changing the behavior will require the developer to have a mongo instance running).
 - If you add a new feature @croasus @atrivedi, and there's no good way to test it yet, let me know your thoughts on what we should add.

**Comment by aromatt** [comment]
I'm going to get the UI side of this going ASAP so that I can more safely refactor UI code.

**Comment by aromatt** [comment]
I think this ticket is done.
- Recording HTTP with Nock works (see https://github.com/aromatt/thejub.pub/blob/master/test/server/gapi_image_search.js)
- `test/baseline` was rewritten in node
- We have integration testing via https://github.com/aromatt/thejub.pub/blob/master/test/bin/run-nightwatch-tests
- I chose Selenium as the headless browser and am currently giving nightwatch a spin
- I've got some scaffolding in place for mocking mongoose in tests (using mockgoose)

For UI testing, see https://github.com/aromatt/thejub.pub/blob/master/test/ui/test_title.js for an example.
