### ISSUE TITLE
select all and delete not capturing all items in a playlist (leaves 11th-18th tracks)

### ISSUE THREAD

**Issue by acowinthecrowd** [aromatt/thejub.pub#200]
Recreation steps (if this doesn't work on your machine let me know and I'll add screen caps)
1. Load this playlist ID into FreePlay: PL9B20E0AA37B49F6E
2. Activate select all
3. Press delete button

I'm left with 8 unchecked videos that I've confirmed were checked when check all was used. These are the 11th-18th tracks.

I tried this with a different 22 track playlist, same results. 11th-18th remain.

Tried with a 13 track playlist, 11th-13th remain.

Tried with a 211 track playlist, and it leaves 97 tracks. Another iteration of select all/delete leaves 8 again. I didn't have the patience to figure out which 97 are left, but the list is here: PLEA-YTCJIHOO7gKxWOF2B42EVcmfnVtEk. If you could load it backwards, it could be useful because they are almost all numbered in the track title.

**Comment by aromatt** [comment]
I think this is the same as https://github.com/aromatt/thejub.pub/issues/188, but I'll close that one since you have more detail.

**Comment by acowinthecrowd** [comment]
Also wonky things happen when just manually selecting specific tracks and deleting.

Wonky in this case is some of the selected tracks don't delete and some do.

**Comment by jeskaeli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#200: select all and delete not capturing all items in a playlist (leaves 11th-18th tracks)](https://trello.com/c/oq5NUBX6/32-200-select-all-and-delete-not-capturing-all-items-in-a-playlist-leaves-11th-18th-tracks)
