### ISSUE TITLE
Update jubbot help text

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/thejub.pub#206]
Please add instructions about how to apply a color to your username.

Also, the current text reads: "Give someone karma with '++username', and check someone's karma with '!karma username'."

Recommend adding:
"Give someone karma with '++username', and check someone's karma with '!karma username', or simply look at the Who's Jubbin' list to see each jub's total karma."

Or something like that :)

**Comment by aromatt** [comment]
Fixed by https://github.com/aromatt/thejub.pub/commit/215565b82e2055cfac523a18a072fd24b5e416e2
