### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by aromatt** [aromatt/thejub.pub#220]
Free certs https://letsencrypt.org
Tool that may be helpful https://certbot.eff.org/

**Comment by aromatt** [comment]
Apparently some older browsers might not support Let's Encrypt certs, but also apparently certs from e.g. Godaddy or Symantec are really cheap now?

**Comment by aromatt** [comment]
The server is now running behind nginx.  Next we'll set up nginx with Let's Encrypt.

**Comment by jeskaeli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use https #220 ?](https://trello.com/c/F1oWTLCA/2-use-https-220)

**Comment by aromatt** [comment]
This is done.  Let's see what trello does
