### ISSUE TITLE
Jubbot should announce a track's trimmed length, not untrimmed

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/thejub.pub#228]
I don't think it's valuable to display the untrimmed length of a track in the jubbot announcement. In fact, I think it's confusing. Display the total length **post trim** in the announcement, as is done in the playlist, Up Next, and currently playing countdown timer.

**Comment by aromatt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jubbot should announce a track's trimmed length, not untrimmed #228](https://trello.com/c/QTMy7oNg/8-jubbot-should-announce-a-track-s-trimmed-length-not-untrimmed-228)

**Comment by croasus** [comment]
Fixed by pull request #253
