### ISSUE TITLE
jubbot: That's what she said!

### ISSUE THREAD

**Issue by aromatt** [aromatt/thejub.pub#230]
http://www.aclweb.org/anthology/P11-2016

**Comment by acowinthecrowd** [comment]
This never really worked out with coolestbot. Are we sure we want to open this can of worms?

**Comment by aromatt** [comment]
Haha that's true... only if I can find something better than that one we used for coolestbot

**Comment by aromatt** [comment]
I've created a "bot ideas" wiki page.
