### ISSUE TITLE
Unable to log in/password reset not sending

### ISSUE THREAD

**Issue by acowinthecrowd** [aromatt/thejub.pub#248]
I was told I had an invalid username/password when logging in. I used password reset, put in username (not email) and was told a reset link had been sent, but after about 60 minutes, have not received it.

**Comment by aromatt** [comment]
Before I forget: this must be a case sensitivity issue because acowinthecrowd has some extra accounts that are permutations of his username. Deleting all the extra user accounts should fix this

**Comment by acowinthecrowd** [comment]
Whatever happened tonight around 9:45 solved the issue for me
