### ISSUE TITLE
Display info about next queued track

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/thejub.pub#26]
Display somewhere the name and length of the next upcoming track queued up, whether it is from a different DJ or from the next track in the current playlist if there is only one DJ.

Display a prompt if no video is queued up, such as "Nothing in queue" or "None" or something like that.

**Comment by aromatt** [comment]
depends on #4

**Comment by jeskaeli** [comment]
@aromatt Are you planning on implementing the prompt when there is nothing coming up next?

**Comment by croasus** [comment]
Should this be closed? Or is it left open based on @jeskaeli 's comment? Or to remind us that this feature should be included in the playlist redesign?

**Comment by aromatt** [comment]
I actually kinda like it the way it is right now.  If the UI changes so that there's an obvious box-off blank space that looks weird without words in it, then I think we should do it.
