### ISSUE TITLE
Display an indicator when a member mutes the music

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/thejub.pub#30]
Some kind of indicator could be implemented to communicate to the DJ (and everyone else) that a person or group of people have clicked 'Mute' and are not currently hearing the track.

For example:
![muted](https://cloud.githubusercontent.com/assets/14909827/10201163/9c92d854-6778-11e5-8214-961695827867.png)

If there is resistance to this, it could also be an option (enable/disable mute indicator).

**Comment by aromatt** [comment]
We'll wait on #73 (in which user state is centralized instead of distributed among clients), after which this feature will be simple

**Comment by aromatt** [comment]
I'm going to pick this one up next.

**Comment by croasus** [comment]
I'll give this one a shot unless @aromatt still wants to do it.

**Comment by aromatt** [comment]
forgot about this one haha.  go for it!
