### ISSUE TITLE
Allow copy+paste of formatted text into chat input box

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/thejub.pub#33]
Allow users to copy+paste formatted text, such as:

"The UPD will be PW'D this WKND. So if you will be at the OPIS using AMS OR JIRA please use the MPL.   Or as I like to call it   UPWOAJM   for short.

UPD:  Upper Parking Deck
PW'D: Pressure Washed
WKND: Weekend
OPIS: Office
AMS: Account Management System
JIRA: A truncation of Gojira, the Japanese name for Godzilla
MPL: MEDITECH Parking Lot"

Current behavior if that text is copied into chat:

"The UPD will be PW'D this WKND. So if you will be at the OPIS using AMS OR JIRA please use the MPL.   Or as I like to call it   UPWOAJM   for short.  UPD:  Upper Parking Deck PW'D: Pressure Washed WKND: Weekend OPIS: Office AMS: Account Management System JIRA: A truncation of Gojira, the Japanese name for Godzilla MPL: MEDITECH Parking Lot"

**Comment by aromatt** [comment]
We might now be able to paste text with newlines in it (the bot needed this ability for the welcome message). Let me know if it works for you. If there are other formatting issues, we'll tackle them individually.

**Comment by aromatt** [comment]
Never mind... even though the server can handle it now, the text input field doesn't seem to support it.

**Comment by jeskaeli** [comment]
duplicated by #229
