### ISSUE TITLE
chat history should be persistent

### ISSUE THREAD

**Issue by acowinthecrowd** [aromatt/thejub.pub#34]
Steps to recreate:
1. Open jub.dj
2. Begin chatting
3. Close jub.dj
4. Open jub.dj

What I expect to happen
All previous chat should still be there

What actually happens
Chat history is completely erased

**Comment by aromatt** [comment]
I like jess's idea of doing this per-day, so you'd only see the chat history for the current day.  @acowinthecrowd what do you think?

**Comment by acowinthecrowd** [comment]
Per day is a great idea.

**Comment by baronpumpky** [comment]
+1

**Comment by aromatt** [comment]
I might also store any message mentioning people while they were offline. So if you log off on Monday afternoon and someone mentions you Monday night, you'll see those messages Tuesday morning, even though the persistent history clears out each day.

Another approach to this whole thing would be to store some capped amount of history at all times, which just drops old messages as new ones show up.  That would probably be easiest.

**Comment by acowinthecrowd** [comment]
Status request

**Comment by aromatt** [comment]
At some point soon we'll be adding in persistence (nothing is persistent now except user settings stored in cookies) and this will get picked up along with that wave of updates.

**Comment by aromatt** [comment]
I just realized that I probably won't use the database for this.  If we only keep 1 day's worth of chat history, I think it should fit in about 2MB (assuming a max of about 12 messages per minute, and an average of 50 characters per message, plus a timestamp and user name), so I can just store this in memory or store it in a daily-rotating file.

**Comment by aromatt** [comment]
I'll pick this one up next

**Comment by acowinthecrowd** [comment]
EXCITED SQUEEEEE
