### ISSUE TITLE
Recognize links in text

### ISSUE THREAD

**Issue by acowinthecrowd** [aromatt/thejub.pub#35]
Steps to recreate:
1. Send a chat message that includes a link

What I expect to happen
link is transformed into a clickable hyperlink

What actually happens
link text is unclickable; treated as normal text

**Comment by atrivedi** [comment]
I will take this

**Comment by acowinthecrowd** [comment]
I think this should be reopened. Links should show as links no matter their place in the message

**Comment by aromatt** [comment]
fair enough

**Comment by atrivedi** [comment]
I agree. And I have an idea for a solution. This will work for images, too!

**Comment by acowinthecrowd** [comment]
Stop takin pics of pluto and get on it!

**Comment by atrivedi** [comment]
I have busy - will @ soon
