### ISSUE TITLE
display linked images in chat

### ISSUE THREAD

**Issue by acowinthecrowd** [aromatt/thejub.pub#36]
Steps to recreate:
Send a link to an image in a chat message

What I expect to happen
The image (scaled down obvi) is displayed in the chat window

What actually happens
Image link is treated as regular text

**Comment by atrivedi** [comment]
I'm taking a look at this now

**Comment by aromatt** [comment]
If we do this, we should provide a way to disable it -- users have different SFW expectations.

**Comment by atrivedi** [comment]
This is another one I'd like to tackle if you haven't begun already.

what should the UI be? In order to help with NSFW images, we could have an upload image thing and on the upload UI the user can tag it NSFW. Each user also has a "Hide NSFW images toggle" somehwere. Or should it interpret `(.jpeg | .jpg | .png ...)` and just convert it to `<img>` (which forces the end user to hide each NSFW image)

**Comment by aromatt** [comment]
I would rather give everyone the option to either show all images or hide them (keep them as clickable links).

**Comment by acowinthecrowd** [comment]
I don't like either of these because the whole point (to me) of the
images being in chat is for reactions to what's said; using the image
in place of a text response.
The upload thing makes it so you can't quickly insert an image as a
response, and the leaving it as a link makes it so you can't do it at
all, quick or not.

**Comment by acowinthecrowd** [comment]
So we decided on a display/hide all images toggle. A global toggle, if you will. And that toggle should NOT be retroactive. If you were on hidden, and images were posted, if you now switch to display, those past ones should stay hidden.

**Comment by atrivedi** [comment]
I most certainly will

I'll do get at this after i fix that other thing

**Comment by atrivedi** [comment]
I've been meaning to get to this, but I've been busy. If y'all can wait a bit longer, I'd still like to get at it. Otherwise, you can tackle it.

**Comment by aromatt** [comment]
it's all you bro
