### ISSUE TITLE
For issue #44, would be awesome if that chat line was in a different color

### ISSUE THREAD

**Issue by csumsky3** [aromatt/thejub.pub#49]
This is super minor (but also i think super easy to implement?), but it would be really helpful if the chat line that posts for issue #44 was in a different color (maybe that teal?), just so it's really easy to find as you scroll up the list to look for them.

**Comment by aromatt** [comment]
which teal?

**Comment by csumsky3** [comment]
The one that "Report bug or request feature" is in. But that was just an example. Just a different, standy-outy color would be nice.

**Comment by atrivedi** [comment]
I would like to take a stab at this

**Comment by aromatt** [comment]
What color are you thinking? I should have responded - I kinda like it the way it is.  if you're already working on it let's figure out what looks best.

**Comment by atrivedi** [comment]
i haven't started. But I do like the idea of the coloring the "this song is playing" panel differently

**Comment by aromatt** [comment]
ohhh I do like the idea of changing the *panel* color.  We could use the color of the DJ who started the track.

**Comment by aromatt** [comment]
and maybe do some effect on it like darken it

**Comment by atrivedi** [comment]
perfect! may i?

**Comment by aromatt** [comment]
please!

**Comment by atrivedi** [comment]
:+1:

**Comment by atrivedi** [comment]
if a color is already dark, should we lighten it?

**Comment by aromatt** [comment]
I think they should all be fairly dark to fit in a little better with the rest of the chat history.  let's see how that looks?

**Comment by aromatt** [comment]
@atrivedi we think that the best bang for bucks would be to do a border in a more saturated color (maybe even the original color, but... maybe not)

**Comment by aromatt** [comment]
a thin border ( <= 5px?) with square corners would do nicely

**Comment by atrivedi** [comment]
I'll update it soon - got a busy week ahead, but we'll see

**Comment by aromatt** [comment]
No rush - I think it looks fine for now

**Comment by aromatt** [comment]
I think we have satisfied this ticket now.  We'll tweak as needed.

**Comment by atrivedi** [comment]
`twerk` as needed

**Comment by aromatt** [comment]
+1

**Comment by csumsky3** [comment]
Lol
