### ISSUE TITLE
bot command to show a random face from textfac.es

### ISSUE THREAD

**Issue by csumsky3** [aromatt/thejub.pub#55]
Some shortcut / autocomplete that lets you post these faces into jub chat http://textfac.es/

**Comment by aromatt** [comment]
I vote this becomes a bot feature

**Comment by csumsky3** [comment]
so you chat at some bot and he spits one back?

**Comment by aromatt** [comment]
maybe the bot just scans all chats for "face".  could be funny

**Comment by aromatt** [comment]
moved to wiki
