### ISSUE TITLE
Many videos are restricted from play - Running list kept here

### ISSUE THREAD

**Issue by acowinthecrowd** [aromatt/thejub.pub#77]
I'm running into so many videos that are restricted from play by third party sites. I can't recall coming across any of these on plug, and I know for a fact some of them I did indeed play

**Comment by acowinthecrowd** [comment]
https://www.youtube.com/watch?v=oTTHOFNJZEo
https://www.youtube.com/watch?v=Q-xPRA2j2Mg
https://www.youtube.com/watch?v=MAcgjwUy3oc

Anything from VEVO

**Comment by aromatt** [comment]
I'm not sure we'll be able to do anything about this without paying money to upgrade my YouTube API account.  We'll see.

**Comment by acowinthecrowd** [comment]
Look into it; I couldn't find anything. All I could find that hinted at the
API being a fee service is that it isn't, but they limit the requests you
can send.

**Comment by acowinthecrowd** [comment]
Ever look into this?

**Comment by aromatt** [comment]
I haven't yet.  When you get a chance can you paste the exact message the player shows when this happens? I will then google that message along with "youtube iframe player"

**Comment by acowinthecrowd** [comment]
Apparently some VEVO is permitted

**Comment by acowinthecrowd** [comment]
The videos listed above and one tested vevo video (Taylor swift blank space) played successfully so this issue should be closed. If other videos are discovered as unplayable, a new issue will be started or this one will be reopened.
