### ISSUE TITLE
Add ability to manually order tracks in queue

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/thejub.pub#79]
For example, I'd like to be able to queue up a particular video and make it play as my next track, even if I've already got a long list queued up.

I recommend first step just being a 'Move to top' function - we can work around that until you can do a more polished drag/drop or alternative ordering system.

For example, on the Netflix queue, you can manually edit the number of each entry. Upon submission, the entries are ordered to respect those edits.

**Comment by aromatt** [comment]
I'm starting on this

**Comment by aromatt** [comment]
I'm going to add "move to top" and "remove from queue"

**Comment by aromatt** [comment]
https://github.com/aromatt/thejub.pub/commit/22b38526ec8798cccd836d2651a151d7d1c3d727 adds checkboxes to tracks and 'move to top' and 'delete' buttons which appear when any tracks are checked.

I plan to add more time-saving improvements like:
- context menu for quick one-off deletes/moves
- shift + click for faster multi-select
- drag and drop to reorder

I'll create a new ticket for those
