### ISSUE TITLE
Stop queue from autofocusing to the top when edited

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/thejub.pub#84]
When I remove tracks, the queue automatically scrolls back to the top. This makes it more complicated to keep an eye on what track(s) is being removed - if I add 30 tracks, then delete 10, I have to keep scrolling down to see what has been removed and when to stop hitting 'unqueue'.

Even if tracks can be removed from anywhere in the queue in the future, I think the best behavior would be for the queue to never auto-scroll at any point. If the list is edited, keep the scroll where it is regardless.

**Comment by aromatt** [comment]
I'll grab this one next.

**Comment by jeskaeli** [comment]
aromatt, I believe this has already been resolved. When I make changes to a playlist, the list is not re-focused to the top anymore.

**Comment by croasus** [comment]
I agree with @jeskaeli - this seems to be fixed.
