### ISSUE TITLE
Queue track titles not truncated correctly

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/thejub.pub#87]
![queue issues](https://cloud.githubusercontent.com/assets/14909827/10610082/5d1a7cb2-7714-11e5-9ea2-b37a631842ae.png)

**Comment by aromatt** [comment]
There's a chance for this to happen when the queue goes from no-scroll-bar to scoll-bar.  There is a line that tries to account for the width of the scroll bar, but it only knows to do this is the scroll bar is already there.  

There are a few ways to fix this that involve drawing the queue twice back to back, but that would be expensive so it would be nice to try to estimate, before we try to draw it, whether or not the latest size of the queue will end up causing a scroll bar to be drawn.

**Comment by aromatt** [comment]
The fix for this is to wait to call `truncate()` on each track title until they are all drawn

**Comment by aromatt** [comment]
Pretty sure we won't see this anymore.
