### ISSUE TITLE
Add "whisper" to chat

### ISSUE THREAD

**Issue by aromatt** [aromatt/thejub.pub#88]
maybe "/whisper [username] ..." to send a private message to a user.  I don't want it to be too easy to have a totally private conversation, since that would be at odds with the goals of the site.

**Comment by acowinthecrowd** [comment]
No need for whisper within plug. There's enough media available if you want to send a private message. I wouldn't even want that functionality in plug

**Comment by aromatt** [comment]
sweet, less work for me...
