### ISSUE TITLE
Allow users to have multiple browser windows open

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/thejub.pub#89]
Currently unable to add anything to my queue. Queue button and 'enter' both do nothing.

**Comment by aromatt** [comment]
Currently the server will only send the user's queue over ONE socket (the most recently-seen one).  The site does not force users to user a single browser instance, so queuing should not break when a user has more than one open.

**Comment by aromatt** [comment]
This should work now, I'll reopen if it doesn't.
